"""empty message

Revision ID: 6d908f825a6c
Revises: 
Create Date: 2021-03-23 16:05:28.365689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d908f825a6c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=80), nullable=True),
    sa.Column('title', sa.String(length=80), nullable=True),
    sa.Column('descript', sa.String(length=80), nullable=True),
    sa.Column('room', sa.String(length=80), nullable=True),
    sa.Column('bathroom', sa.String(length=80), nullable=True),
    sa.Column('price', sa.String(length=80), nullable=True),
    sa.Column('location', sa.String(length=80), nullable=True),
    sa.Column('propertyT', sa.String(length=80), nullable=True),
    sa.Column('photo', sa.LargeBinary(length=2048), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bathroom'),
    sa.UniqueConstraint('descript'),
    sa.UniqueConstraint('filename'),
    sa.UniqueConstraint('location'),
    sa.UniqueConstraint('price'),
    sa.UniqueConstraint('propertyT'),
    sa.UniqueConstraint('room'),
    sa.UniqueConstraint('title')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('properties')
    # ### end Alembic commands ###
